name: Build and Deploy
on:
  push:
    branches:
      - develop
    paths: [
        "web/components/**/*.tsx",
        "web/style/theme.ts",
        "web/.storybook/*.js",
      ] # Trigger the action only when files change in the folders defined here
permissions:
  contents: write
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout üõéÔ∏è
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false
      - name: Install and Build
        working-directory: ./web
        run: | # Install npm packages and build the Storybook files
          npm ci
          npm run storybook:build
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: docs/storybook # The branch the action should deploy to.
          folder: web/storybook-static # The folder that the build-storybook script generates files.
          clean: true # Automatically remove deleted files from the deploy branch
          clean-exclude: |
            .gitignore
            docs/.gitignore
          target-folder: docs # The folder that we serve our Storybook files from
          token: ${{ secrets.GITHUB_TOKEN }}
